const KEYS = [
  [
    {
      keyId: 'Backquote',
      class: 'key_backquote',
      eng: { down: '`', shift: '~', caps: '`' },
      rus: { down: 'ё', shift: 'Ё', caps: 'Ё' },
    },
    {
      keyId: 'Digit1',
      class: 'key_1',
      eng: { down: '1', shift: '!', caps: '1' },
      rus: { down: '1', shift: '!', caps: '1' },
    },
    {
      keyId: 'Digit2',
      class: 'key_2',
      eng: { down: '2', shift: '@', caps: '2' },
      rus: { down: '2', shift: '"', caps: '2' },
    },
    {
      keyId: 'Digit3',
      class: 'key_3',
      eng: { down: '3', shift: '#', caps: '3' },
      rus: { down: '3', shift: '№', caps: '3' },
    },
    {
      keyId: 'Digit4',
      class: 'key_4',
      eng: { down: '4', shift: '$', caps: '4' },
      rus: { down: '4', shift: ';', caps: '4' },
    },
    {
      keyId: 'Digit5',
      class: 'key_5',
      eng: { down: '5', shift: '%', caps: '5' },
      rus: { down: '5', shift: '%', caps: '5' },
    },
    {
      keyId: 'Digit6',
      class: 'key_6',
      eng: { down: '6', shift: '^', caps: '6' },
      rus: { down: '6', shift: ':', caps: '6' },
    },
    {
      keyId: 'Digit7',
      class: 'key_7',
      eng: { down: '7', shift: '&', caps: '7' },
      rus: { down: '7', shift: '?', caps: '7' },
    },
    {
      keyId: 'Digit8',
      class: 'key8',
      eng: { down: '8', shift: '*', caps: '8' },
      rus: { down: '8', shift: '*', caps: '8' },
    },
    {
      keyId: 'Digit9',
      class: 'key_9',
      eng: { down: '9', shift: '(', caps: '9' },
      rus: { down: '9', shift: '(', caps: '9' },
    },
    {
      keyId: 'Digit0',
      class: 'key_0',
      eng: { down: '0', shift: ')', caps: '0' },
      rus: { down: '0', shift: ')', caps: '0' },
    },
    {
      keyId: 'Minus',
      class: 'key_minus',
      eng: { down: '-', shift: '_', caps: '-' },
      rus: { down: '-', shift: '_', caps: '-' },
    },
    {
      keyId: 'Equal',
      class: 'key_equal',
      eng: { down: '=', shift: '+', caps: '=' },
      rus: { down: '=', shift: '+', caps: '=' },
    },
    {
      keyId: 'Backspace',
      class: 'key_backspace',
      eng: { down: 'backspace', shift: 'backspace', caps: 'backspace' },
      rus: { down: 'backspace', shift: 'backspace', caps: 'backspace' },
    },
  ],
  [
    {
      keyId: 'Tab',
      class: 'key_tab',
      eng: { down: 'tab', shift: 'tab', caps: 'tab' },
      rus: { down: 'tab', shift: 'tab', caps: 'tab' },
    },
    {
      keyId: 'KeyQ',
      class: 'key_q',
      eng: { down: 'q', shift: 'Q', caps: 'Q' },
      rus: { down: 'й', shift: 'Й', caps: 'Й' },
    },
    {
      keyId: 'KeyW',
      class: 'key_w',
      eng: { down: 'w', shift: 'W', caps: 'W' },
      rus: { down: 'ц', shift: 'Ц', caps: 'Ц' },
    },
    {
      keyId: 'KeyE',
      class: 'key_e',
      eng: { down: 'e', shift: 'E', caps: 'E' },
      rus: { down: 'у', shift: 'У', caps: 'У' },
    },
    {
      keyId: 'KeyR',
      class: 'key_r',
      eng: { down: 'r', shift: 'R', caps: 'R' },
      rus: { down: 'к', shift: 'К', caps: 'К' },
    },
    {
      keyId: 'KeyT',
      class: 'key_t',
      eng: { down: 't', shift: 'T', caps: 'T' },
      rus: { down: 'е', shift: 'Е', caps: 'Е' },
    },
    {
      keyId: 'KeyY',
      class: 'key_y',
      eng: { down: 'y', shift: 'Y', caps: 'Y' },
      rus: { down: 'н', shift: 'Н', caps: 'Н' },
    },
    {
      keyId: 'KeyU',
      class: 'key_u',
      eng: { down: 'u', shift: 'U', caps: 'U' },
      rus: { down: 'г', shift: 'Г', caps: 'Г' },
    },
    {
      keyId: 'KeyI',
      class: 'key_i',
      eng: { down: 'i', shift: 'I', caps: 'I' },
      rus: { down: 'ш', shift: 'Ш', caps: 'Ш' },
    },
    {
      keyId: 'KeyO',
      class: 'key_o',
      eng: { down: 'o', shift: 'O', caps: 'O' },
      rus: { down: 'щ', shift: 'Щ', caps: 'Щ' },
    },
    {
      keyId: 'KeyP',
      class: 'key_p',
      eng: { down: 'p', shift: 'P', caps: 'P' },
      rus: { down: 'з', shift: 'З', caps: 'З' },
    },
    {
      keyId: 'BracketLeft',
      class: 'key_bracket-left',
      eng: { down: '[', shift: '{', caps: '[' },
      rus: { down: 'х', shift: 'Х', caps: 'Х' },
    },
    {
      keyId: 'BracketRight',
      class: 'key_bracket-right',
      eng: { down: ']', shift: '}', caps: ']' },
      rus: { down: 'ъ', shift: 'Ъ', caps: 'Ъ' },
    },
    {
      keyId: 'Backslash',
      class: 'key_backslash',
      eng: { down: '\\', shift: '|', caps: '\\' },
      rus: { down: '\\', shift: '/', caps: '\\' },
    },
    {
      keyId: 'Delete',
      class: 'key_delete',
      eng: { down: 'delete', shift: 'delete', caps: 'delete' },
      rus: { down: 'delete', shift: 'delete', caps: 'delete' },
    },
  ],
  [
    {
      keyId: 'CapsLock',
      class: 'key_capslock',
      eng: { down: 'capslock', shift: 'capslock', caps: 'CAPSLOCK' },
      rus: { down: 'capslock', shift: 'capslock', caps: 'CAPSLOCK' },
    },
    {
      keyId: 'KeyA',
      class: 'key_a',
      eng: { down: 'a', shift: 'A', caps: 'A' },
      rus: { down: 'ф', shift: 'Ф', caps: 'Ф' },
    },
    {
      keyId: 'KeyS',
      class: 'key_s',
      eng: { down: 's', shift: 'S', caps: 'S' },
      rus: { down: 'ы', shift: 'Ы', caps: 'Ы' },
    },
    {
      keyId: 'KeyD',
      class: 'key_d',
      eng: { down: 'd', shift: 'D', caps: 'D' },
      rus: { down: 'в', shift: 'В', caps: 'В' },
    },
    {
      keyId: 'KeyF',
      class: 'key_f',
      eng: { down: 'f', shift: 'F', caps: 'F' },
      rus: { down: 'а', shift: 'А', caps: 'А' },
    },
    {
      keyId: 'KeyG',
      class: 'key_g',
      eng: { down: 'g', shift: 'G', caps: 'G' },
      rus: { down: 'п', shift: 'П', caps: 'П' },
    },
    {
      keyId: 'KeyH',
      class: 'key_h',
      eng: { down: 'h', shift: 'H', caps: 'H' },
      rus: { down: 'р', shift: 'Р', caps: 'Р' },
    },
    {
      keyId: 'KeyJ',
      class: 'key_j',
      eng: { down: 'j', shift: 'J', caps: 'J' },
      rus: { down: 'о', shift: 'О', caps: 'О' },
    },
    {
      keyId: 'KeyK',
      class: 'key_k',
      eng: { down: 'k', shift: 'K', caps: 'K' },
      rus: { down: 'л', shift: 'Л', caps: 'Л' },
    },
    {
      keyId: 'KeyL',
      class: 'key_l',
      eng: { down: 'l', shift: 'L', caps: 'L' },
      rus: { down: 'д', shift: 'Д', caps: 'Д' },
    },
    {
      keyId: 'Semicolon',
      class: 'key_semicolon',
      eng: { down: ';', shift: ':', caps: ';' },
      rus: { down: 'ж', shift: 'Ж', caps: 'Ж' },
    },
    {
      keyId: 'Quote',
      class: 'key_quote',
      eng: { down: '\'', shift: '"', caps: '\'' },
      rus: { down: 'э', shift: 'Э', caps: 'Э' },
    },
    {
      keyId: 'Enter',
      class: 'key_enter',
      eng: { down: 'enter', shift: 'enter', caps: 'enter' },
      rus: { down: 'enter', shift: 'enter', caps: 'enter' },
    },
  ],
  [
    {
      keyId: 'ShiftLeft',
      class: 'key_shift',
      eng: { down: 'shift', shift: 'SHIFT', caps: 'SHIFT' },
      rus: { down: 'shift', shift: 'SHIFT', caps: 'SHIFT' },
    },
    {
      keyId: 'IntlBackslash',
      class: 'key_backslash-left',
      eng: { down: '\\', shift: '|', caps: '\\' },
      rus: { down: '\\', shift: '/', caps: '\\' },
    },
    {
      keyId: 'KeyZ',
      class: 'key_z',
      eng: { down: 'z', shift: 'Z', caps: 'Z' },
      rus: { down: 'я', shift: 'Я', caps: 'Я' },
    },
    {
      keyId: 'KeyX',
      class: 'key_x',
      eng: { down: 'x', shift: 'X', caps: 'X' },
      rus: { down: 'ч', shift: 'Ч', caps: 'Ч' },
    },
    {
      keyId: 'KeyC',
      class: 'key_c',
      eng: { down: 'c', shift: 'C', caps: 'C' },
      rus: { down: 'с', shift: 'С', caps: 'С' },
    },
    {
      keyId: 'KeyV',
      class: 'key_v',
      eng: { down: 'v', shift: 'V', caps: 'V' },
      rus: { down: 'м', shift: 'М', caps: 'М' },
    },
    {
      keyId: 'KeyB',
      class: 'key_b',
      eng: { down: 'b', shift: 'B', caps: 'B' },
      rus: { down: 'и', shift: 'И', caps: 'И' },
    },
    {
      keyId: 'KeyN',
      class: 'key_n',
      eng: { down: 'n', shift: 'N', caps: 'N' },
      rus: { down: 'т', shift: 'Т', caps: 'Т' },
    },
    {
      keyId: 'KeyM',
      class: 'key_m',
      eng: { down: 'm', shift: 'M', caps: 'M' },
      rus: { down: 'ь', shift: 'Ь', caps: 'Ь' },
    },
    {
      keyId: 'Comma',
      class: 'key_comma',
      eng: { down: ',', shift: '<', caps: ',' },
      rus: { down: 'б', shift: 'Б', caps: 'Б' },
    },
    {
      keyId: 'Period',
      class: 'key_period',
      eng: { down: '.', shift: '>', caps: '.' },
      rus: { down: 'ю', shift: 'Ю', caps: 'Ю' },
    },
    {
      keyId: 'Slash',
      class: 'key_slash',
      eng: { down: '/', shift: '?', caps: '/' },
      rus: { down: '.', shift: ',', caps: '.' },
    },
    {
      keyId: 'ArrowUp',
      class: 'key_up',
      eng: { down: '▴', shift: '▴', caps: '▴' },
      rus: { down: '▴', shift: '▴', caps: '▴' },
    },
    {
      keyId: 'ShiftRight',
      class: 'key_shift',
      eng: { down: 'shift', shift: 'SHIFT', caps: 'SHIFT' },
      rus: { down: 'shift', shift: 'SHIFT', caps: 'SHIFT' },
    },
  ],
  [
    {
      keyId: 'ControlLeft',
      class: 'key_ctrl',
      eng: { down: 'ctrl', shift: 'ctrl', caps: 'ctrl' },
      rus: { down: 'ctrl', shift: 'ctrl', caps: 'ctrl' },
    },
    {
      keyId: 'MetaLeft',
      class: 'key_win',
      eng: { down: 'win', shift: 'win', caps: 'win' },
      rus: { down: 'win', shift: 'win', caps: 'win' },
    },
    {
      keyId: 'AltLeft',
      class: 'key_alt',
      eng: { down: 'alt', shift: 'alt', caps: 'alt' },
      rus: { down: 'alt', shift: 'alt', caps: 'alt' },
    },
    {
      keyId: 'Space',
      class: 'key_space',
      eng: { down: ' ', shift: ' ', caps: ' ' },
      rus: { down: ' ', shift: ' ', caps: ' ' },
    },
    {
      keyId: 'AltRight',
      class: 'key_alt',
      eng: { down: 'alt', shift: 'alt', caps: 'alt' },
      rus: { down: 'alt', shift: 'alt', caps: 'alt' },
    },
    {
      keyId: 'ArrowLeft',
      class: 'key_left',
      eng: { down: '◂', shift: '◂', caps: '◂' },
      rus: { down: '◂', shift: '◂', caps: '◂' },
    },
    {
      keyId: 'ArrowDown',
      class: 'key_down',
      eng: { down: '▾', shift: '▾', caps: '▾' },
      rus: { down: '▾', shift: '▾', caps: '▾' },
    },
    {
      keyId: 'ArrowRight',
      class: 'key_right',
      eng: { down: '▸', shift: '▸', caps: '▸' },
      rus: { down: '▸', shift: '▸', caps: '▸' },
    },
    {
      keyId: 'ControlRight',
      class: 'key_ctrl',
      eng: { down: 'ctrl', shift: 'ctrl', caps: 'ctrl' },
      rus: { down: 'ctrl', shift: 'ctrl', caps: 'ctrl' },
    }],
];

export default KEYS;
